apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: jane
---
apiVersion: v1
kind: Secret
metadata:
  name: netflll
  namespace: jane
data:
  netflix: bm9zZWNyZXQ=
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: jane
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jane
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/nginx:1.14.2
        ports:
        - containerPort: 80

